### PR TITLE
feat: add fastapi

### PR DESCRIPTION
**Pull request by emirot**

### CODE REVIEW

**Comment by emirot** [comment]
@mingrammer is that something that could be added?

**Review by mingrammer — APPROVED** [review]
LGTM! Sorry for late!

**Comment by emirot** [comment]
No thank you! I guess next step is to run list2md.py  and do another PR?

**Comment by mingrammer** [comment]
Yep. Please send me a PR!

**Comment by emirot** [comment]
https://github.com/mingrammer/python-web-framework-stars/pull/8

**Pull request merged**
